name: 'Product Launch Event'
description: 'product-launch-event'
id: 'f4af988b-6568-4aee-2bb3-08db50014549'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Mssql'
  version: '1.0.0'
sourceSystems:
  - name: 'erp'
    description: 'ERP'
    id: '963df8c5-e464-4584-83f8-ff3734e75456'
  - name: 'POS'
    description: 'POS'
    id: 'a86540c3-707b-4e4a-b19f-2317c01d045b'
version: 'v1.1'
